#include "cheats.hpp"
#include "plugin.hpp"

// 作成者名をここに必ず定義してください．
const char *Creater_name = "Mr.zkr";

const char *invincible_note = "You will be invincible. You will also appear blinking on other people's screens online.";
const char *alwaysStarPower_note = "You will always have star effects, such as invincibility and color.";
const char *alwaysBlackKart_note = "Your kart will be black as if you got bloopered.";
const char *alwaysShocked_note = "Your kart will always be small as if you got shocked.";
const char *alwaysCrushed_note = "Your kart will always be flat as if you got crushed. This is only visible on opponents screens online. On your screen, you'll appear normally.";
const char *instantMT_note = "You will instantly get red and blue MiniTurbos when drifting.";
const char *hugeBunnyhop_note = "You will jump very high when hopping before a drift.";
const char *TwoHundredCC_note = "You will go 200cc speeds. Restart the race after applying the code for the effect to take place.";
const char *FiveHundredCC_note = "You will go 500cc speeds. Restart the race after applying the code for the effect to take place.";
const char *CC9000_note = "You will go 9000cc speeds. Restart the race after applying the code for the effect to take place.";
const char *fastReverse_note = "You will reverse at higher speeds than before when holding B.";
const char *moonjump_note = "Y +　DU　+　R　=　Enable";
const char *saveSlotTeleporter_note = "-ST　+　X　= Save Current Position\n-ST + Y = Load Saved Position";
const char *itemWheel_note = "L+DL=Lucky 7 L+DD=Star　L+DR=Blooper　R+DL=Blue　shell R+DD=Lightning　R+DR=Bullet　bill X+DL=Red　Shell　X+DD=Bom-Omb X+DR=Green shell Y+DL=Tanooki　Tail　Y+DD=Banana　Y+DR=Fire　Flower";
const char *dropMushrooms_note = "This code replaces green shells with droppable mushrooms. Throw a 'green shell' to drop a mushroom.";
const char *fastBlueShell_note = "Blue shells will go very fast.";
const char *stoppedBlueShell_note = "Blue shells will not move after being thrown.";
const char *fastGreenShell_note = "Green shells will go very fast.";
const char *stoppedGreenShell_note = "Green shells will not move after being thrown.";
const char *bulletControl_note = "A+B+DR=ON　A+B+DL=OFF";
const char *bulletSpeed_note = "-A = Very Fast\n-B = Stopped\n-Y = Normal Speed";
const char *blueShellRide_note = "-L　+　Y　+　DU　= Enable\nYou will warp to a blue shell and ride it.";
const char *disableStarMusic_note = "The star music won't play when you're in a star.";
const char *maxTimer_note = "The timer will freeze at 4:59.9xx.";
const char *waterEverywhere_note = "You will always be underwater.";
const char *noCountdown_note = "You will be able to drive when the countdown normally would be happening.";
const char *disableFirstPersonView_note = "You will not be able to activate first person view by pressing Up on the D-Pad.";
const char *NoDC_note = "You will not get disconnected unless the cause of the disconnection is an actual network problem.";
const char *randomVR_note = "A random VR value will be generated.";
const char *unlockEverything_note = "Everything will be unlocked. After enabling, save the game by completing a time trial or something, exit the game, and open it again. At this point everything should be permanently unlocked.";
const char *driveAnywhere_note = "-R +　SE　+　DL = Disable\n-R　+　SE　+　DR = Enable\n-R　+　Y +　DU　=　Go Up\n-R　+　Y　+　DD　= Go Down";
const char *stalking_note = "-ST + DR = Increase\n-ST + DL = Decrease\n-ST + DU = Stalk the player until code is disabled\n-Hold ST to stalk the player temporarily, release ST to stop stalking\n-ST + DD = Disable Code";
const char *TouchCode_note = "Touch the bottom screen or drag your stylus across it to warp your kart to that position on the map!";
const char *fastGame_note = "The game will move at a very fast speed. Unstable, use at your own risk!";
const char *eliminationMode_note = "Every 30 seconds, the player in last place will be eliminated. The last player standing wins! This mode works best in rooms with more players.";
const char *tagMode_note = "One player will be 'it' and they have to try and tag another player by running into them! You will lose points the longer you are 'it' and also gain points for not being 'it'. The tagged person can will always be in a star.";
const char *shineTheif_note = "One player will start off with the 'shine' and they have to protect it from other people, who will try to steal it by running into the player with the shine! You will gain points the longer you have the shine. The person with the shine will always be in a star.\nD-Pad Left = Use Gained Boost";
const char *instantAcceleration_note = "Your kart will instantly accelerate to the maximum speed when pressing A.";
const char *instantBackAcceleration_note = "Your kart will instantly accelerate to it's maximum reverse speed when pressing B.";
const char *instantStop_note = "Your kart will instantly come to a complete stop when pressing A+B.";
const char *trickAnywhere_note = "You will be able to perform a trick anywhere by pressing R.";
const char *ItemBattle_note = "It is the same as Item Hack of Item Codes.";
const char *CoBTpts_note = "R + X +　DU=Plus Points R+X+DD=Minus　Points";
const char *All99k_note = "Please save something with the setting of Mario Kart channel.";
const char *vrM_note = "ST=1 X=1000 DD=5000 DU=99999 DR=50000 DL=10000";
const char *vrExtender_note = "ST=654321 X=350000 DU=999999 DR=123456 DD=777777 DL=0";
const char *vrE2_note = "ST=512810 X=454545 DU=114514 DR=931810 DD=364364 DL=191919";
const char *vrE3_note = "ST=427427 X=564731 DU=375641 DR=444444 DD=427311 DL=564219";

void my_menus(void)
{
	new_spoiler("Kart Codes");
		new_entry_with_note("Invincibility", invincible_note, invincible);
		new_entry_with_note("Always Star Power", alwaysStarPower_note, alwaysStarPower);
		new_entry_with_note("Always Black Kart", alwaysBlackKart_note, alwaysBlackKart);
		new_entry_with_note("Always Shocked", alwaysShocked_note, alwaysShocked);
		new_entry_with_note("Always Crushed", alwaysCrushed_note, alwaysCrushed);
		new_entry("Always Slip Stream", ASS);
		new_entry_with_note("Trick Anywhere", trickAnywhere_note, trickAnywhere);
		new_entry_with_note("Instant MiniTurbo", instantMT_note, instantMT);
		new_entry("Instant Respawn", IRP);
		new_entry_with_note("Bullet Bill Control (See Note)", bulletControl_note, bulletControl);
		new_entry_with_note("Huge Bunnyhop", hugeBunnyhop_note, hugeBunnyhop);
	exit_spoiler();
	
	new_spoiler("Speed & Movement Codes");
		new_entry_with_note("200cc", TwoHundredCC_note, TwoHundredCC);
		new_entry_with_note("500cc", FiveHundredCC_note, FiveHundredCC);
		new_entry_with_note("9000cc", CC9000_note, CC9000);
		new_entry_with_note("Instant Acceleration", instantAcceleration_note, instantAcceleration);
		new_entry_with_note("Instant Backwards Acceleration", instantBackAcceleration_note, instantBackAcceleration);
		new_entry_with_note("Instant Stop", instantStop_note, instantStop);
		new_entry_with_note("Fast Reverse Speeds", fastReverse_note, fastReverse);
		new_entry_with_note("Stalking Hack (See Note)", stalking_note, stalking);
		new_entry_with_note("Touch Screen Teleporter", TouchCode_note, TouchCode);
		new_entry_with_note("Moonjump (See Note)", moonjump_note, moonjump);
		new_entry_with_note("Drive Anywhere (See Note)", driveAnywhere_note, driveAnywhere);
		new_entry_with_note("Save Slot Teleporter (See Note)", saveSlotTeleporter_note, saveSlotTeleporter);
	exit_spoiler();
	
	new_spoiler("Item Codes");
		new_entry_with_note("Item Hack (See Note)", itemWheel_note, itemWheel);
		new_entry_with_note("Drop Mushrooms (See Note)", dropMushrooms_note, dropMushrooms);
		new_entry_with_note("Fast Blue Shell", fastBlueShell_note, fastBlueShell);
		new_entry_with_note("Stopped Blue Shell", stoppedBlueShell_note, stoppedBlueShell);
		new_entry_with_note("Fast Green Shell", fastGreenShell_note, fastGreenShell);
		new_entry_with_note("Stopped Green Shell", stoppedGreenShell_note, stoppedGreenShell);
		new_entry_with_note("Bullet Speed Modifier (See Note)", bulletSpeed_note, bulletSpeed);
		new_entry_with_note("Blue Shell Ride (See Note)", blueShellRide_note, blueShellRide);
		new_entry_with_note("Disable Star Music", disableStarMusic_note, disableStarMusic);
	exit_spoiler();
	
	new_spoiler("Course Codes");
		new_entry_with_note("CPU Brawl", invincible_note, cpuBrawl); // this code hasn't been tested
		new_entry("Auto Pilot", AutoPilot);
		new_entry_with_note("Water Everywhere", waterEverywhere_note, waterEverywhere);
	exit_spoiler();
	
	new_spoiler("Battle Codes");
	    new_entry_with_note("Item Hack (No Blue Shell)", ItemBattle_note, ItemBattle);
		new_entry_with_note("Max Timer", maxTimer_note, maxTimer);
	    new_entry_with_note("Control Battle Pts", CoBTpts_note, CoBTpts);
	exit_spoiler();
	
	new_spoiler("Menu & Unlock Codes");
		new_entry_with_note("No Countdown", noCountdown_note, noCountdown);
		new_entry_with_note("Disable First Person View", disableFirstPersonView_note, disableFirstPersonView);
		new_entry_with_note("No Disconnect", NoDC_note, NoDC);
		new_entry_with_note("Fast Game/Anti-Matrix", fastGame_note, fastGame);
		new_entry_with_note("Unlock Everything", unlockEverything_note, unlockEverything);
	    new_entry_with_note("Status All 99999 (See Note)", All99k_note, All99k);
	exit_spoiler();
	
	new_spoiler("VR Extender & Pts Codes");
	    new_entry_with_note("Random VR", randomVR_note, randomVR);
		new_spoiler("Modify the VR button");
		    new_entry_with_note("Select VR Modifiler (See Note)", vrM_note, vrM);
			new_entry_with_note("Select VR Extender (See Note)", vrExtender_note, vrExtender);
	        new_entry_with_note("KITANAI Select VR Extender (See Note)", vrE2_note, vrE2);
	        new_entry_with_note("BOUGEN Select VR Extender (See Note)", vrE3_note, vrE3);
	    exit_spoiler();
	    new_spoiler("Normal VR");
	        new_entry("1 VR", vr1);
	        new_entry("1000 VR", vr1000);
	        new_entry("5000 VR", vr5000);
	        new_entry("10000 VR", vr10000);
	        new_entry("50000 VR", vr50000);
	        new_entry("99999 VR", vr99999);
        exit_spoiler();
	    new_spoiler("Numeric word Cheat VR");
	        new_entry("114514 VR", vr114514);
	        new_entry("931810 VR", vr931810);
	        new_entry("512810 VR", vr512810);
	        new_entry("454545 VR", vr454545);
	        new_entry("191919 VR", vr191919);
	        new_entry("364364 VR", vr364364);
	        new_entry("375641 VR", vr375641);
	        new_entry("564219 VR", vr564219);
	        new_entry("564731 VR", vr564731);
	        new_entry("427311 VR", vr427311);
	        new_entry("427427 VR", vr427427);
	    exit_spoiler();
        new_spoiler("Other Cheat VR");
	        new_entry("0 VR", vr0);
	        new_entry("999999 VR", vr999999);
	        new_entry("696969 VR", vr696969);
	        new_entry("420000 VR", vr420000);
	        new_entry("495000 VR", vr495000);
	        new_entry("350000 VR", vr350000);
	        new_entry("355555 VR", vr355555);
	        new_entry("199998 VR", vr199998);
	        new_entry("655534 VR", vr655534);
	        new_entry("200102 VR", vr200102);
	    exit_spoiler();
        new_spoiler("Other Cheat VR 2");
            new_entry("123456 VR", vr123456);
            new_entry("654321 VR", vr654321);
            new_entry("888888 VR", vr888888);
            new_entry("777777 VR", vr777777);
            new_entry("666666 VR", vr666666);
            new_entry("555555 VR", vr555555);
            new_entry("444444 VR", vr444444);
            new_entry("333333 VR", vr333333);
            new_entry("222222 VR", vr222222);
            new_entry("111111 VR", vr111111);
            new_entry("100000 VR", vr100000);
        exit_spoiler();
        new_spoiler("Pts Extender");
            new_entry("40 Pts", pts40);
            new_entry("255 Pts", pts255);
            new_entry("999 Pts", pts999);
        exit_spoiler();
	exit_spoiler();
	
	new_spoiler("Custom Game Modes");
		new_entry_with_note("Shine Thief", shineTheif_note, shineTheif);
		new_entry_with_note("Tag", tagMode_note, tagMode);
		new_entry_with_note("Elimination Mode", eliminationMode_note, eliminationMode);
	exit_spoiler();
	
	new_spoiler("Region & Flag Codes");
		new_spoiler("Normal Region Codes");
            new_entry("Africa", region_Africa);
		    new_entry("Argentina", region_Argentina);
		    new_entry("Australia", region_Australia);
		    new_entry("China", region_China);
		    new_entry("Cuba", region_Cuba);
		    new_entry("France", region_France);
		    new_entry("Hawaii", region_Hawaii);
		    new_entry("Haiti", region_Haiti);
		    new_entry("Iran", region_Iran);
		    new_entry("Iceland", region_Iceland);
		    new_entry("Phillippines", region_Phillippines);
		    new_entry("Northern Phillippines", region_NorthernPhillippines);
		    new_entry("Russia", region_Russia);
		    new_entry("Saudi Arabia", region_SaudiArabia);
		    new_entry("United States (America)", region_UnitedStates);
		exit_spoiler();
		new_spoiler("Cheat Region Codes");
		    new_entry("North Pole", region_NorthPole);
		    new_entry("Northern Pole", region_NorthernPole);
		    new_entry("Northern Antartica", region_NorthernAntartica);
		    new_entry("Upper Antartica", region_UpperAntartica);
		    new_entry("Lower Antartica", region_LowerAntartica);
		    new_entry("Lower Antartica 2", region_LowerAntartica2);
		    new_entry("More Antartica", region_MoreAntartica);
		    new_entry("More Antartica 2", region_MoreAntartica2);
		    new_entry("More Antartica 3", region_MoreAntartica3);
		    new_entry("More Antartica 4", region_MoreAntartica4);
		    new_entry("More Antartica 5", region_MoreAntartica5);
		    new_entry("More Antartica 6", region_MoreAntartica6);
		    new_entry("wtf", region_wtf);
		    new_entry("wtf 2", region_wtf2);
		    new_entry("wtf 3", region_wtf3);
		    new_entry("Unknown", region_Unknown);
		    new_entry("Spaghetti Noppers", region_SpaghettiNoppers);
		exit_spoiler();
		new_spoiler("Flag Codes");
		    new_entry("Antigua and Barbuda", flag_AntiguaAndBarbuda);
		    new_entry("Argentina", flag_Argentina);
		    new_entry("Australia", flag_Australia);
		    new_entry("Belize", flag_Belize);
		    new_entry("Brazil", flag_Brazil);
		    new_entry("British Virgin Islands", flag_BritishVirginIslands);
		    new_entry("Canada", flag_Canada);
		    new_entry("Chile", flag_Chile);
		    new_entry("China", flag_China);
		    new_entry("Dominica", flag_Dominica);
		    new_entry("Denmark", flag_Denmark);
		    new_entry("Ecuador", flag_Ecuador);
		    new_entry("Finland", flag_Finland);
		    new_entry("France", flag_France);
		    new_entry("Germany", flag_Germany);
		    new_entry("Greece", flag_Greece);
		exit_spoiler();
	    new_spoiler("Flag Codes 2");
	        new_entry("Haiti", flag_Haiti);
	        new_entry("Iceland", flag_Iceland);
	        new_entry("Italy", flag_Italy);
	        new_entry("India", flag_India);
	        new_entry("Japan", flag_Japan);
	        new_entry("New Zealand", flag_NewZealand);
	        new_entry("Panama", flag_Panama);
	        new_entry("Russia", flag_Russia);
	        new_entry("South Africa", flag_SouthAfrica);
	        new_entry("South Korea", flag_SouthKorea);
	        new_entry("Saudi Arabia", flag_SaudiArabia);
	        new_entry("Taiwan", flag_Taiwan);
	        new_entry("United States (America)", flag_UnitedStates);
	        new_entry("United Kingdom (England)", flag_UnitedKingdom);
	        new_entry("Uruguay", flag_Uruguay);
	        new_entry("US Virgin Islands", flag_USVirginIslands);
	    exit_spoiler();
	exit_spoiler();
	
	new_spoiler("Lightning Limiter Online");
	    new_entry("Activate with X Code by FC", lightningLimiterOnline);
	exit_spoiler();
	
}

